### ISSUE TITLE
Error when using stratified_split[BUG]

### ISSUE THREAD

**Issue by sgaseretto** [ShopRunner/collie#41]
**Describe the bug**

I'm using my own dataset based on movielens and each time I try to split the data it gives me this error

```
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
```

To try and see if I was doing something else wrong, I run the [Quickstart](https://github.com/ShopRunner/collie/blob/main/tutorials/quickstart.ipynb) exactly as it is, the only difference is that i used my own dataset and prepared it with the following code:

```python
movielens_df = pd.read_csv('movielens-metadata/ratings_small.csv', delimiter=';')
movielens_df.rename(columns={'userId':'user_id', 'movieId':'item_id'}, inplace=True)
movielens_df['rating'] = movielens_df['rating'].transform(lambda x : float(x.replace(',','.')))
df = movielens_df
```
But then if I use the `read_movielens_df` it works perfectly. Also this problem only occurs when using `stratified_split`, I tested `random_split` and it worked fine.

Here is the dataset if you want to try it yourself
[ratings_small.csv](https://github.com/ShopRunner/collie/files/7723187/ratings_small.csv)

**Comment by nathancooperjones** [comment]
Hi @sgaseretto. 

Perfect timing! Right now, we have a ticket to make this issue a lot more transparent (something that @emmafgrimes is actually going to work on in the next week, funnily enough), but the short answer is that the error is a valid one, but the error message itself is awful. 

Currently, the stratified split attempts to ensure that every user appears in both the training and validation datasets, but when you have a user who only has one interaction, the function can't do the split properly and complains with this obscure error. To circumvent this, I would suggest using this function before doing a stratified split: 

https://github.com/ShopRunner/collie/blob/0963998ded3eb566fda863ad462ab5bec6bcd223/collie/utils.py#L168 

The ticket we have to fix this is just improving the error message, but I wonder if we should maybe also include a flag, something like `ignore_warnings` that, when in this situation, just puts that user with a single interaction in the training dataset and doesn't error out at all. 

What do you think of this idea @sgaseretto @emmafgrimes?

**Comment by emmafgrimes** [comment]
Hi @nathancooperjones & @sgaseretto: 

I think adding a parameter like `ignore_warnings` to `stratified_split` is a great idea. I still think improving the error message when `ignore_warnings = False` is worthwhile as well.

**Comment by sgaseretto** [comment]
First of all, thanks for the really fast response!! It helped a lot. Also I agree with you both about the flag parameter. I'm digging into the code of `stratified_split` to understand it better because something odd happened. For this particular dataset, only after using `min_num_of_interactions=23` the `stratified_split` worked fine, but using a number smaller than 23 kept returning the error.

**Comment by nathancooperjones** [comment]
Sorry for the delayed response on this again @sgaseretto! 

When I try to use the dataset you attached above with `stratified_split`, I don't seem to get an error. Here's the code block I am using to test this out: 

```python
from collie.cross_validation import random_split, stratified_split
from collie.interactions import Interactions
import pandas as pd

df = pd.read_csv('/Users/nathan.jones/Downloads/ratings_small.csv', sep=';')
df = df.drop_duplicates(subset=['movieId', 'userId'])

df['userId'].value_counts().min()  # output: 19

interactions = Interactions(users=df['userId'], items=df['movieId'], allow_missing_ids=True)

stratified_split(interactions, test_p=0.2)
```

I would expect the split to break when we have an interactions dataset with a user that only appears once in the dataset, such as the following example built off the last: 

```python
new_df = (
    df
    .append(
        other=[
            {'movieId': df['movieId'].max() + 1, 'userId': df['userId'].max() + 1},
        ],
        ignore_index=True,
    )
)

interactions = Interactions(users=new_df['userId'], items=new_df['movieId'], allow_missing_ids=True)

stratified_split(interactions, test_p=0.2)  # raises the ``ValueError``
```

_But_, taking this same example and adding in the ``remove_users_with_fewer_than_n_interactions`` call, it works now, which is what I would expect. 

```python
from collie.utils import remove_users_with_fewer_than_n_interactions


new_df = (
    df
    .append(
        other=[
            {'movieId': df['movieId'].max() + 1, 'userId': df['userId'].max() + 1},
        ],
        ignore_index=True,
    )
)

# added line
new_df = remove_users_with_fewer_than_n_interactions(df=new_df, min_num_of_interactions=2, user_col='userId')

interactions = Interactions(users=new_df['userId'], items=new_df['movieId'], allow_missing_ids=True)

stratified_split(interactions, test_p=0.2)  # works now!
```

Alternatively, if we instead appended two rows to that `df`, such that that user appeared _twice_ in the dataset instead of only once, the split should work as expected, even if we do not call the ``remove_users_with_fewer_than_n_interactions`` function. 

```python
new_df = (
    df
    .append(
        other=[
            {'movieId': df['movieId'].max() + 1, 'userId': df['userId'].max() + 1},
            {'movieId': df['movieId'].max() + 2, 'userId': df['userId'].max() + 1},  # added line
        ],
        ignore_index=True,
    )
)

interactions = Interactions(users=new_df['userId'], items=new_df['movieId'], allow_missing_ids=True)

stratified_split(interactions, test_p=0.2)  # works too!
```

Can you attach the code block you were using where you got that error with a number smaller than `23`? We are very interested in fixing this bug! 

Happy holidays!
